export const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORGANIZATION_ADMIN: 'ORGANIZATION_ADMIN',
  ADMIN: 'ADMIN',
  HR_MANAGER: 'HR_MANAGER',
  PAYROLL_MANAGER: 'PAYROLL_MANAGER',
  HR_PAYROLL_MANAGER: 'HR_PAYROLL_MANAGER',
  HR_PAYROLL_USER: 'HR_PAYROLL_USER',
  FINANCE_MANAGER: 'FINANCE_MANAGER',
  DEPARTMENT_MANAGER: 'DEPARTMENT_MANAGER',
  EMPLOYEE: 'EMPLOYEE',
  AUDITOR: 'AUDITOR',
};

export const CONTRACT_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  TERMINATED: 'TERMINATED',
};

export const PAYRUN_STATUS = {
  DRAFT: 'DRAFT',
  COMPUTING: 'COMPUTING',
  COMPUTED: 'COMPUTED',
  WARNINGS_FOUND: 'WARNINGS_FOUND',
  VALIDATED: 'VALIDATED',
  PAID: 'PAID',
  CANCELLED: 'CANCELLED',
};

export const LEAVE_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
};

export const ALLOCATION_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REFUSED: 'REFUSED',
  EXPIRED: 'EXPIRED',
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  LATE: 'LATE',
  EARLY_LEAVE: 'EARLY_LEAVE',
  ON_LEAVE: 'ON_LEAVE',
  OVERTIME: 'OVERTIME',
  MISSING_CHECKOUT: 'MISSING_CHECKOUT',
  HOLIDAY: 'HOLIDAY',
};

export const COOKIE_NAMES = {
  ACCESS_TOKEN: 'odoo_access_token',
  REFRESH_TOKEN: 'odoo_refresh_token',
};
