export const PERMISSIONS = {
  // Platform & Organization
  PLATFORM_MANAGE: 'platform.manage',
  ORGANIZATION_READ: 'organization.read',
  ORGANIZATION_UPDATE: 'organization.update',
  ORGANIZATION_MANAGE: 'organization.manage',

  // User Management
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',

  // Employee Lifecycle
  EMPLOYEES_READ_ALL: 'employees.read.all',
  EMPLOYEES_READ_TEAM: 'employees.read.team',
  EMPLOYEES_READ_OWN: 'employees.read.own',
  EMPLOYEES_CREATE: 'employees.create',
  EMPLOYEES_UPDATE: 'employees.update',
  EMPLOYEES_DELETE: 'employees.delete',

  // Attendance
  ATTENDANCE_READ_ALL: 'attendance.read.all',
  ATTENDANCE_READ_TEAM: 'attendance.read.team',
  ATTENDANCE_READ_OWN: 'attendance.read.own',
  ATTENDANCE_MANAGE: 'attendance.manage',
  ATTENDANCE_CLOCK: 'attendance.clock',

  // Leaves & Time Off
  LEAVE_READ_ALL: 'leave.read.all',
  LEAVE_READ_TEAM: 'leave.read.team',
  LEAVE_READ_OWN: 'leave.read.own',
  LEAVE_APPLY: 'leave.apply',
  LEAVE_APPROVE: 'leave.approve',
  LEAVE_CANCEL: 'leave.cancel',

  // Payroll & Payslips
  PAYROLL_READ_ALL: 'payroll.read.all',
  PAYROLL_READ_OWN: 'payroll.read.own',
  PAYROLL_RUN: 'payroll.run',
  PAYROLL_APPROVE: 'payroll.approve',
  PAYROLL_EXPORT: 'payroll.export',
  PAYSLIPS_READ_ALL: 'payslips.read.all',
  PAYSLIPS_READ_OWN: 'payslips.read.own',

  // Finance & Cost Centers
  FINANCE_READ: 'finance.read',
  FINANCE_APPROVE: 'finance.approve',
  REIMBURSEMENTS_MANAGE: 'reimbursements.manage',

  // Reports
  REPORTS_READ: 'reports.read',
  REPORTS_EXPORT: 'reports.export',
  REPORTS_HR: 'reports.hr',
  REPORTS_PAYROLL: 'reports.payroll',
  REPORTS_FINANCE: 'reports.finance',

  // Audit & Security
  AUDIT_READ: 'audit.read',
  AUDIT_EXPORT: 'audit.export',
  SECURITY_READ: 'security.read',
  SETTINGS_MANAGE: 'settings.manage',
};

export const ROLE_PERMISSIONS = {
  SUPER_ADMIN: [
    PERMISSIONS.PLATFORM_MANAGE,
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_MANAGE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SETTINGS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
  ],

  ORGANIZATION_ADMIN: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.EMPLOYEES_READ_ALL,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.EMPLOYEES_DELETE,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_READ_ALL,
    PERMISSIONS.PAYROLL_RUN,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.PAYSLIPS_READ_ALL,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_HR,
    PERMISSIONS.REPORTS_PAYROLL,
    PERMISSIONS.REPORTS_FINANCE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  ADMIN: [
    // Legacy alias for ORGANIZATION_ADMIN
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.EMPLOYEES_READ_ALL,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.EMPLOYEES_DELETE,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.PAYROLL_READ_ALL,
    PERMISSIONS.PAYROLL_RUN,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.PAYSLIPS_READ_ALL,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.REPORTS_HR,
    PERMISSIONS.REPORTS_PAYROLL,
    PERMISSIONS.REPORTS_FINANCE,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.SETTINGS_MANAGE,
  ],

  HR_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.EMPLOYEES_READ_ALL,
    PERMISSIONS.EMPLOYEES_CREATE,
    PERMISSIONS.EMPLOYEES_UPDATE,
    PERMISSIONS.ATTENDANCE_READ_ALL,
    PERMISSIONS.ATTENDANCE_MANAGE,
    PERMISSIONS.LEAVE_READ_ALL,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_HR,
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.PAYSLIPS_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_APPLY,
  ],

  PAYROLL_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.EMPLOYEES_READ_ALL,
    PERMISSIONS.PAYROLL_READ_ALL,
    PERMISSIONS.PAYROLL_RUN,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.PAYSLIPS_READ_ALL,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_PAYROLL,
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.PAYSLIPS_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_APPLY,
  ],

  HR_PAYROLL_MANAGER: [
    // Legacy alias for PAYROLL_MANAGER
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.EMPLOYEES_READ_ALL,
    PERMISSIONS.PAYROLL_READ_ALL,
    PERMISSIONS.PAYROLL_RUN,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.PAYSLIPS_READ_ALL,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_PAYROLL,
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.PAYSLIPS_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_APPLY,
  ],

  HR_PAYROLL_USER: [
    // Legacy alias
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.EMPLOYEES_READ_ALL,
    PERMISSIONS.PAYROLL_READ_ALL,
    PERMISSIONS.PAYSLIPS_READ_ALL,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_PAYROLL,
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.PAYSLIPS_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_APPLY,
  ],

  FINANCE_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.PAYROLL_READ_ALL,
    PERMISSIONS.PAYROLL_APPROVE,
    PERMISSIONS.PAYROLL_EXPORT,
    PERMISSIONS.FINANCE_READ,
    PERMISSIONS.FINANCE_APPROVE,
    PERMISSIONS.REIMBURSEMENTS_MANAGE,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_FINANCE,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.PAYSLIPS_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_APPLY,
  ],

  DEPARTMENT_MANAGER: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.EMPLOYEES_READ_TEAM,
    PERMISSIONS.ATTENDANCE_READ_TEAM,
    PERMISSIONS.LEAVE_READ_TEAM,
    PERMISSIONS.LEAVE_APPROVE,
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.PAYSLIPS_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_APPLY,
  ],

  EMPLOYEE: [
    PERMISSIONS.EMPLOYEES_READ_OWN,
    PERMISSIONS.ATTENDANCE_READ_OWN,
    PERMISSIONS.ATTENDANCE_CLOCK,
    PERMISSIONS.LEAVE_READ_OWN,
    PERMISSIONS.LEAVE_APPLY,
    PERMISSIONS.LEAVE_CANCEL,
    PERMISSIONS.PAYSLIPS_READ_OWN,
  ],

  AUDITOR: [
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.AUDIT_READ,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.SECURITY_READ,
    PERMISSIONS.REPORTS_READ,
    PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.PAYROLL_READ_ALL,
  ],
};

export function hasPermission(userRole, requiredPermission) {
  if (!userRole) return false;
  if (userRole === 'SUPER_ADMIN') return true;
  if (userRole === 'ORGANIZATION_ADMIN' || userRole === 'ADMIN') return true;
  const permissions = ROLE_PERMISSIONS[userRole] || [];
  return permissions.includes(requiredPermission);
}
